fps: 20
env:
  name: mimicgen
  task: HammerCleanup_D0
  state_dim: 75
  action_dim: 7
  episode_length: 400
  meta: hammer_cleanup_env.json
  image_keys:
  - agentview
  - robot0_eye_in_hand
  state_keys:
  - object
  - robot0_joint_pos
  - robot0_joint_pos_cos
  - robot0_joint_pos_sin
  - robot0_joint_vel
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_eef_vel_lin
  - robot0_eef_vel_ang
  - robot0_gripper_qpos
  - robot0_gripper_qvel
  - robot0_contact
  - robot0_eef_force_norm
