# @package _global_

fps: 20

env:
  name: mimicgen
  task: Stack_D0
  state_dim: 9
  action_dim: 7
  episode_length: 200
  meta: stack_d0_env.json
  image_keys:
  - agentview
  - robot0_eye_in_hand
  state_keys:
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_gripper_qpos

  # These should match the policy requirements
  use_delta_action: true
  use_highres_image_obs: false
