# @package _global_

fps: 20

env:
  name: mimicgen
  task: ThreePieceAssembly_D0
  state_dim: 108
  action_dim: 7
  episode_length: 450
  meta: three_piece_assembly_env.json
  image_keys:
  - agentview
  - robot0_eye_in_hand
  state_keys:
  - object
  - robot0_joint_pos
  - robot0_joint_pos_cos
  - robot0_joint_pos_sin
  - robot0_joint_vel
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_eef_vel_lin
  - robot0_eef_vel_ang
  - robot0_gripper_qpos
  - robot0_gripper_qvel
  - robot0_eef_pos_rel_base
  - robot0_eef_quat_rel_base
  - robot0_eef_pos_rel_piece_1
  - robot0_eef_quat_rel_piece_1
  - robot0_eef_pos_rel_piece_2
  - robot0_eef_quat_rel_piece_2
